CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    delivery_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    done boolean,
    projectId integer REFERENCES projects(id)
);

-- PROJECTS

INSERT INTO projects(name, priority, description, delivery_date)
VALUES ('Make a Web App', 1, 'Usando JS', '2019-05-12');

INSERT INTO projects(name, priority, description, delivery_date)
VALUES ('Make a Mobile App', 2, 'Usando Dark', '2019-07-12');

INSERT INTO projects(name, priority, description, delivery_date)
VALUES ('Make a Desktop App', 2, 'Usando TS', '2019-09-12');

-- TAKS

INSERT INTO tasks(nombre, done, projectId)
VALUES ('download vuejs', false, 1);

INSERT INTO tasks(nombre, done, projectId)
VALUES ('install vuejs', false, 1)

INSERT INTO tasks(nombre, done, projectId)
VALUES ('Download flutter', false, 2)

INSERT INTO tasks(nombre, done, projectId)
VALUES ('Desing UI', false, 2)
